server:
  port: 8084

spring:
  application:
    name: KAFKA
  datasource:
    password: pass
    url: jdbc:postgresql://localhost:5430/evrekadb
    username: anton
    driver: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_SERVICE_URL:http://localhost:9092}
    listener:
      ack-mode: manual